### ISSUE TITLE
How to use with kube-system namespace components?

### ISSUE THREAD

**Issue by alisalmaji** [brancz/kube-rbac-proxy#172]
As you described that your use case to writing this project was to securing nodeexporter, how we can use this to secure somethings like kube-proxy or coredns metrics url?

This components are in kube-system namespace and there is a probability to be overwritten by kubespary .

Is it best practice to inject sidecar with kube-system components?

**Comment by ibihim** [comment]
As the current maintainer, I must admit that I don't have extensive expertise in Prometheus. Nonetheless, I'll do my best to help you.

If you're concerned about kubespray overwriting your configuration, you might be able to set an exception for kube-rbac-proxy.
Indeed, kube-rbac-proxy is typically run as a sidecar container. You can find examples in the "examples" folder of the project repository.
kube-rbac-proxy can protect any container, as it performs a SubjectAccessReview for the client making a request. If you prefer, you can enable static authorization or use rewrites with templated resource attributes to customize the authorization process.

I will be closing this issue since it was created last year. If the problem still persists, please feel free to reopen it, and we can continue the discussion.

Additionally, I plan to work on improving the documentation this year to provide better guidance and assistance for users like you. Your feedback is greatly appreciated, and we hope to make the project even more user-friendly in the future.

Thank you for your understanding and patience.
