### ISSUE TITLE
Question: K8S cluster version compatibility

### ISSUE THREAD

**Issue by ShacharMalachi** [brancz/kube-rbac-proxy#221]
Hi,

Is the latest release (v0.14.0) compatible with 1.24.X k8s cluster version? (specifically 1.24.7 or above)

Thanks,
Shachar.

**Comment by ibihim** [comment]
We version bump always to the latest k8s dependency in order to be on the safe side. Therefore I can only tell that 1.26 and 1.25 should work according to the [k8s version skew policy](https://kubernetes.io/releases/version-skew-policy/).

1.24 could work as well as the API that kube-rbac-proxy uses to verify AUTHN / AUTHZ to the apiserver is rather stable. E.g. [Authorization V1 SubjectAccessReview](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#subjectaccessreview-v1-authorization-k8s-io) exists even in 1.19.

**Comment by ibihim** [comment]
Feel free to reopen with a follow up. We close issues quickly to avoid clutter.

**Comment by ShacharMalachi** [comment]
Hi @ibihim 

Great, thanks for the answer!

**Comment by yjian118** [comment]
Hi @ibihim Since this issue was closed a long time ago, I want to check the compatibility on newer versions of the k8s cluster(v1.26-v1.28). 
Further, it will be great if we can maintain a compatibility table if possible
