### ISSUE TITLE
Request: Please make FIPS 140-2 compliant images available

### ISSUE THREAD

**Issue by gesarki** [brancz/kube-rbac-proxy#289]
At Acquia we’re currently using this component as part of our globally distributed Kubernetes infrastructure.

Like most providers, we expend a lot of effort ensuring that we remain compliant with varied regulatory regimes across different localities. Currently we're working towards FIPS compliance which is required by federal institutions like healthcare, banking, and defense organizations to set cryptographic standards for highly sensitive data.

The FIPS 140-2 encryption compliance requirement poses a common problem that is likely to be shared by any organizations looking to obtain a FEDRAMP certification and which use a myriad of OSS Kubernetes components under the hood.

FIPS compliance stands as a barrier to entry for smaller organizations. Accepting our contribution would take a small step towards lowering that barrier for the general public and other open source projects.

We, and any other cloud based software providers that are building atop Kubernetes, would benefit from the availability of off-the-shelf FIPS-compliant variants of this project’s images.

While many tools exist to tweak deployment manifests, it can be complex and fragile to rebuild upstream images with constraints placed on encryption libraries. This type of change would be far easier to make inside the originating repo.

Internally, we have explored several paths forward to achieve our compliance objectives. We are hoping to be able to contribute the required changes upstream in a way that benefits the community at large and minimizes toil.

Initially, we are requesting that the current maintainers and community consider supporting a FIPS image of kube-rbac-proxy. We have a notional approach to contribute and would like to collaborate.

Please let us know your thoughts in this Issue or by reaching out directly.

At this time, we have an internal approach that we are using on our internal Go-based controllers and other container images. There are some basic requirements that we’d ask to be built into a `-fips` variant including assertions that could live in the upstream build steps or in later CI steps.

What we do internally is:

- Image is built with a FIPS library such as boringcrypto for Go
- Image is based on Amazon Linux 2, Canonical Ubuntu 20.04 or later, or UBI8
- Image has appropriate group and user specified and final image executes in that context
- We assert that binaries call out to boringcrypto via dynamic linking (this is recommended during build but is not required, we will verify this ourselves in our CI/CD infra)

Thank you for your time considering this request as well as your efforts supporting this project!

Acquia KaaS Core Services team

**Comment by ibihim** [comment]
Hm, interesting. At Red Hat we patch Go itself and don't burden the developers and we have a downstream version that builds RHEL-9, so I might lack context.

- Do you have links?
- Is [FIPS 140-2](https://csrc.nist.gov/pubs/fips/140-2/upd2/final) enough to understand your issue?
- Do you plan to contribute this and you are looking for commitment to assist you in getting it merged?

**Comment by ibihim** [comment]
As there is no follow up, I'll close it. I hope the comment helps you on your journey.

**Comment by imuni4fun** [comment]
Hello @ibihim and sorry it took awhile for me to chime in.
> Is [FIPS 140-2](https://csrc.nist.gov/pubs/fips/140-2/upd2/final) enough to understand your issue?

We have the requirement to ensure encryption in-transit (among other requirements) uses FIPS 140-2 certified ciphers. When communicating with the EKS API (we're primarily on AWS), the ciphers must be constrained on the client side. We do this for our Go-based binaries by building them with boringcrypto experiment.

> Do you plan to contribute this and you are looking for commitment to assist you in getting it merged?

We plan to contribute the change in a manner that would be acceptable to the maintainers/community for this repo. We are reaching out to see how that would be received.

> Could you solve it in a way that doesn't force us to support the --fips flag.

Since the EKS API can't restrict ciphers, we need a change on the client side. This is the most straight forward way to accomplish that.

>What about upstream (k8s)?

Unsure what change would make sense here unless we were to have the API itself be able to reject any non-FIPS ciphers. This might be most broad and an attractive solution but AWS has not expressed an interest in supporting this and they own the EKS distribution. Their guidance is that clients must make the change.

Thank you for responding. I hope we can continue this conversation.

**Comment by imuni4fun** [comment]
Also, this 😅 
https://github.com/kubernetes/kubernetes/issues/109666#issuecomment-1109715374
