### ISSUE TITLE
rewrites exampale does not work.

### ISSUE THREAD

**Issue by dongwangdw** [brancz/kube-rbac-proxy#65]
I run this example in ocp 4.4.

But I got this error: `proxy.go:86] Bad Request. The request or configuration is malformed`
And from the code, I found that the client url is not right, and it should have a query parameter as
namespace="default".  Or it will raise error here like the one above. Then I am confused that what does this rewrite means? What is the expected behaviour here.

**Comment by brancz** [comment]
Unless you really understand why you need the rewrite feature, you probably don't need it :) I recommend reading the docs here if you haven't already: https://github.com/brancz/kube-rbac-proxy/tree/master/examples/rewrites#rewriting-subjectaccessreviews-example

That said I think you're right, that the default curl the client runs does not contain the `?namespace=default` query parameter, so it errors out as you said. This is expected, as with a rewrite configuration the parameter to rewrite with _must_ be provided, otherwise we don't know what value to rewrite the SubjectAccessReview with :slightly_smiling_face: .

**Comment by dongwangdw** [comment]
OK. Thanks for explanation. I guess I missed the doc part.
